return {
	require("plugins.conform"),
	require("plugins.catppuccin"),
	require("plugins.nvim-tree"),
	require("plugins.telescope"),
	require("plugins.treesitter"),
	require("plugins.lsp"),
	require("plugins.typescript-tools"),
	require("plugins.cmp"),
	require("plugins.autopairs"),
	require("plugins.autotag"),
	require("plugins.surround"),
	require("plugins.supermaven"),
	require("plugins.luasnip"),
	require("plugins.golf"),
	require("plugins.lualine"),
  require("plugins.lsp_signature"),
  require("plugins.inc-rename"),
  require("plugins.comment"),
}

