name: Create Self-Contained Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  vendor-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git

      - name: Create vendor directory
        run: mkdir -p vendor/plugins

      - name: Download and vendor all plugins
        run: |
          chmod +x scripts/vendor-plugins.sh
          ./scripts/vendor-plugins.sh

      - name: Create vendored configuration
        run: |
          chmod +x scripts/create-vendored-config.sh
          ./scripts/create-vendored-config.sh

      - name: Create release archive
        run: |
          # Create a clean copy without .git
          cp -r . ../nvim-config-vendored
          cd ../nvim-config-vendored
          rm -rf .git .github/workflows

          # Create the archive
          cd ..
          tar -czf nvim-config-${{ github.event.release.tag_name }}.tar.gz nvim-config-vendored/

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../nvim-config-${{ github.event.release.tag_name }}.tar.gz
          asset_name: nvim-config-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Update release description
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;

            const currentBody = context.payload.release.body || '';
            const additionalInfo = `

            ## Self-Contained Installation

            This release includes all plugin dependencies vendored locally. To install:

            1. Download and extract the \`nvim-config-${{ github.event.release.tag_name }}.tar.gz\` asset. This will automatically back up any previously existing Neovim configuration.
               \`\`\`bash
               wget https://github.com/ryanf9802/FitzVim/releases/download/${{ github.event.release.tag_name }}/nvim-config-${{ github.event.release.tag_name }}.tar.gz &&
               tar -xzf nvim-config-${{ github.event.release.tag_name }}.tar.gz &&
               cd nvim-config-vendored && ./install.sh
               \`\`\`
            2. Start Neovim!

            This version is completely self-contained and doesn't require downloading any external dependencies.
            `;

            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id,
              body: currentBody + additionalInfo
            });
